### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by gciftci** [gciftci/UIFactory#3]
- [ ] structure cleanup
- [ ] add a few templates
- [ ] check namespacing
- [ ] coroutines?
- [ ] Finite-state machine?
- [ ] GUI for creating templates? (à la GUI-Designer)
